### ISSUE TITLE
Bug: You can attack while raising a shield;

### ISSUE THREAD

**Issue by yhanruzai** [Ultreon/ControllerX#6] opened 2024-05-26 02:31 UTC
I was running this in some friend's server as a clientside mod and this mod for some reason allowed attacking while you are blocking with a shield. This is, for obvious reasons, broken in any PVP Server and might be detected as a hack.

**Comment by XyperCode** [comment] 2024-05-28 21:25
Uh oh :concern:
Might need to fix that when I have time available.

Although I would recommend to not use any controller mod on known Minecraft servers anyways due to weird movements due to controller sticks. There are a lot of cases of false positives due t use of controller mods.

**Comment by QboiDev** [comment] 2024-08-27 13:50
Can you confirm if this is fixed in [20.1.4+pre.1](https://github.com/Ultreon/ControllerX/releases/tag/20.1.4%2Bpre.1)?
(CurseForge & Modrinth have versions too)

**Comment by QboiDev** [comment] 2024-09-14 06:10
I can confirm on my modpack it doesn't happen anymore. Let me know if it still happens for you.

**Closed by QboiDev** 2024-09-14 06:10 UTC
Labels: bug
